doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    mapping_types:
      enum: string
    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    dql:
      string_functions:
        JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
        MONTH: Oro\ORM\Query\AST\Functions\SimpleFunction
        YEAR: Oro\ORM\Query\AST\Functions\SimpleFunction
        DAY: Oro\ORM\Query\AST\Functions\SimpleFunction
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
