# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                location: '%kernel.project_dir%/public/images/'
    filesystems:
        default_filesystem:
            adapter: default_adapter
            alias: public_upload