twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        categorie: '@App\Service\Categorie\CategorieService'
        produit: '@App\Service\Produit\ProduitService'
        marque: '@App\Service\Marque\MarqueService'
        notificationservice: '@App\Service\NotificationService'
        locales: '%app.locales%'

when@test:
    twig:
        strict_variables: true


