vich_uploader:
    db_driver: orm

    mappings:
        marques:
            uri_prefix: /images/marques
            upload_destination: '%kernel.project_dir%/public/images/marques'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
