vich_uploader:
    db_driver: orm

    mappings:
        marques:
            uri_prefix: /images/marques
            upload_destination: '%kernel.project_dir%/public/images/marques'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        users:
          uri_prefix: /images/users
          upload_destination: '%kernel.project_dir%/public/images/users'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

          inject_on_load: false
          delete_on_update: true
          delete_on_remove: true

        blogs:
          uri_prefix: /images/blogs
          upload_destination: '%kernel.project_dir%/public/images/blogs'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

          inject_on_load: false
          delete_on_update: true
          delete_on_remove: true

        produits:
          uri_prefix: /images/produits
          upload_destination: '%kernel.project_dir%/public/images/produits'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

          inject_on_load: false
          delete_on_update: true
          delete_on_remove: true
