vich_uploader:
    db_driver: orm

    mappings:
        marques:
            uri_prefix: /images/marques
            upload_destination: '%kernel.project_dir%/public/images/marques'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        users:
          uri_prefix: /images/users
          upload_destination: '%kernel.project_dir%/public/images/users'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        blogs:
          uri_prefix: /images/blogs
          upload_destination: '%kernel.project_dir%/public/images/blogs'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        produits:
          uri_prefix: /images/produits
          upload_destination: '%kernel.project_dir%/public/images/produits'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        videos:
          uri_prefix: /videos
          upload_destination: '%kernel.project_dir%/public/videos'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        categories:
          uri_prefix: /images/categories
          upload_destination: '%kernel.project_dir%/public//images/categories'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
